### ISSUE TITLE
python convert_directory.py

### ISSUE THREAD

**Issue by odomojuli** [unnati-xyz/music-generation#4]
> Traceback (most recent call last):
>   File "convert_directory.py", line 21, in <module>
>     convert_wav_files_to_nptensor(new_directory, block_size, max_seq_len, output_filename)
>   File "/Users/odomojuli/music-generation/data_utils/parse_files.py", line 222, in convert_wav_files_to_nptensor
>     X, Y = load_training_example(file, block_size, useTimeDomain=useTimeDomain)
>   File "/Users/odomojuli/music-generation/data_utils/parse_files.py", line 312, in load_training_example
>     x_t = convert_np_audio_to_sample_blocks(data, block_size)
>   File "/Users/odomojuli/music-generation/data_utils/parse_files.py", line 129, in convert_np_audio_to_sample_blocks
>     block = song_np[num_samples_so_far:num_samples_so_far + block_size]
> TypeError: slice indices must be integers or None or have an __index__ method

**Comment by PadmajaVB** [comment]
@odomojuli The issue has been fixed now. Please check the updated version.
